/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { EnvelopeError1 } from '../models/envelopeError1.js';

/**
 * Creates an instance of ErrorEnvelope
 */
interface ErrorEnvelope {
  /** The error context. */
  error: EnvelopeError1;
  additionalProperties?: Record<string, unknown>;
}

export class ErrorEnvelopeError extends ApiError<ErrorEnvelope> {}
