/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import { SnippetOptions, snippetOptionsSchema } from '../snippetOptions.js';

/** This is a container type for one-of types. */
export type Fields2Snippets = boolean | SnippetOptions;

export const fields2SnippetsSchema: Schema<Fields2Snippets> = lazy(() =>
  oneOf([boolean(), snippetOptionsSchema])
);

export namespace Fields2Snippets {
  /**
   * Validation method to narrow down union type to boolean type case.
   *
   * This is Boolean case.
   */
  export function isBoolean(value: unknown): value is boolean {
    return typeof value === 'boolean';
  }

  /**
   * Validation method to narrow down union type to SnippetOptions type case.
   *
   * This is SnippetOptions case.
   */
  export function isSnippetOptions(value: unknown): value is SnippetOptions {
    return isMappedValueValidForSchema(value, snippetOptionsSchema);
  }
}
