/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  isMappedValueValidForSchema,
  lazy,
  oneOf,
  Schema,
} from '../../schema.js';
import { ContentOptions, contentOptionsSchema } from '../contentOptions.js';

/** This is a container type for one-of types. */
export type FieldsContent = boolean | ContentOptions;

export const fieldsContentSchema: Schema<FieldsContent> = lazy(() =>
  oneOf([boolean(), contentOptionsSchema])
);

export namespace FieldsContent {
  /**
   * Validation method to narrow down union type to boolean type case.
   *
   * This is Boolean case.
   */
  export function isBoolean(value: unknown): value is boolean {
    return typeof value === 'boolean';
  }

  /**
   * Validation method to narrow down union type to ContentOptions type case.
   *
   * This is ContentOptions case.
   */
  export function isContentOptions(value: unknown): value is ContentOptions {
    return isMappedValueValidForSchema(value, contentOptionsSchema);
  }
}
