/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { AgentRun, agentRunSchema } from '../models/agentRun.js';
import {
  CreateAgentRunRequest,
  createAgentRunRequestSchema,
} from '../models/createAgentRunRequest.js';
import {
  ListAgentRunsResponse,
  listAgentRunsResponseSchema,
} from '../models/listAgentRunsResponse.js';
import { bigint, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ErrorEnvelopeError } from '../errors/errorEnvelopeError.js';

export class AgentApi extends BaseApi {
  /**
   * The organization's runs, newest first. Pass one page's `next` as the following request's `after`.
   *
   * @param limit Page size, 1-100. Defaults to 20.
   * @param after Pagination cursor: the previous page's `next`.
   * @return Response from the API call
   */
  async listAgentRuns(
    limit?: bigint,
    after?: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListAgentRunsResponse>> {
    const req = this.createRequest('GET', '/v1/agent/runs');
    const mapped = req.prepareArgs({
      limit: [limit, optional(bigint())],
      after: [after, optional(string())],
    });
    req.query('limit', mapped.limit);
    req.query('after', mapped.after);
    req.throwOn(
      400,
      ErrorEnvelopeError,
      'Malformed or unknown query parameter.'
    );
    req.throwOn(401, ErrorEnvelopeError, 'Invalid or missing API key.');
    req.throwOn(404, ErrorEnvelopeError, 'Unknown `after` cursor.');
    req.throwOn(500, ErrorEnvelopeError, 'Unexpected server error.');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(listAgentRunsResponseSchema, requestOptions);
  }

  /**
   * Returns the new run in `pending` state. Poll it by id until `status` reaches a terminal state.
   *
   * @param body
   * @return Response from the API call
   */
  async createAgentRun(
    body: CreateAgentRunRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AgentRun>> {
    const req = this.createRequest('POST', '/v1/agent/runs');
    const mapped = req.prepareArgs({
      body: [body, createAgentRunRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      ErrorEnvelopeError,
      'Malformed body, unknown field, unknown `effort`, or a rejected `output_schema`.'
    );
    req.throwOn(401, ErrorEnvelopeError, 'Invalid or missing API key.');
    req.throwOn(402, ErrorEnvelopeError, 'Insufficient credits.');
    req.throwOn(500, ErrorEnvelopeError, 'Unexpected server error.');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(agentRunSchema, requestOptions);
  }

  /**
   * Poll until `status` reaches a terminal state.
   *
   * @param id The run id.
   * @return Response from the API call
   */
  async getAgentRun(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AgentRun>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/v1/agent/runs/${mapped.id}`;
    req.throwOn(401, ErrorEnvelopeError, 'Invalid or missing API key.');
    req.throwOn(404, ErrorEnvelopeError, 'No such run in this org.');
    req.throwOn(500, ErrorEnvelopeError, 'Unexpected server error.');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(agentRunSchema, requestOptions);
  }

  /**
   * Stop a run that has not finished. Returns the run, unchanged if it had already ended, so cancelling
   * is safe to retry.
   *
   * @param id The run id.
   * @return Response from the API call
   */
  async cancelAgentRun(
    id: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AgentRun>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({ id: [id, string()] });
    req.appendTemplatePath`/v1/agent/runs/${mapped.id}/cancel`;
    req.throwOn(401, ErrorEnvelopeError, 'Invalid or missing API key.');
    req.throwOn(404, ErrorEnvelopeError, 'No such run in this org.');
    req.throwOn(500, ErrorEnvelopeError, 'Unexpected server error.');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(agentRunSchema, requestOptions);
  }
}
