/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AnswerHttpRequest,
  answerHttpRequestSchema,
} from '../models/answerHttpRequest.js';
import {
  AnswerHttpResponse,
  answerHttpResponseSchema,
} from '../models/answerHttpResponse.js';
import { BaseApi } from './baseApi.js';
import { ErrorEnvelopeError } from '../errors/errorEnvelopeError.js';

export class AnswerApi extends BaseApi {
  /**
   * @param body
   * @return Response from the API call
   */
  async answer(
    body: AnswerHttpRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AnswerHttpResponse>> {
    const req = this.createRequest('POST', '/v1/answer');
    const mapped = req.prepareArgs({ body: [body, answerHttpRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      ErrorEnvelopeError,
      'Missing or malformed request fields.'
    );
    req.throwOn(401, ErrorEnvelopeError, 'Invalid or missing API key.');
    req.throwOn(402, ErrorEnvelopeError, 'Insufficient credits.');
    req.throwOn(
      404,
      ErrorEnvelopeError,
      'Endpoint not found, or a scope that matches nothing.'
    );
    req.throwOn(405, ErrorEnvelopeError, 'Wrong method for this endpoint.');
    req.throwOn(
      408,
      ErrorEnvelopeError,
      'The answer did not complete in time.'
    );
    req.throwOn(413, ErrorEnvelopeError, 'Request body is too large.');
    req.throwOn(
      415,
      ErrorEnvelopeError,
      '`Content-Type` is not `application/json`.'
    );
    req.throwOn(
      429,
      ErrorEnvelopeError,
      'Rate limit exceeded. Wait before retrying.'
    );
    req.throwOn(500, ErrorEnvelopeError, 'Unexpected server error.');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(answerHttpResponseSchema, requestOptions);
  }
}
