/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { FetchRequest, fetchRequestSchema } from '../models/fetchRequest.js';
import { FetchResponse, fetchResponseSchema } from '../models/fetchResponse.js';
import { BaseApi } from './baseApi.js';
import { ErrorEnvelopeError } from '../errors/errorEnvelopeError.js';

export class FetchApi extends BaseApi {
  /**
   * @param body
   * @return Response from the API call
   */
  async fetch(
    body: FetchRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<FetchResponse>> {
    const req = this.createRequest('POST', '/v1/fetch');
    const mapped = req.prepareArgs({ body: [body, fetchRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      ErrorEnvelopeError,
      'Malformed body, an out-of-bounds or duplicated `urls` entry, or an unavailable `formats` or `tier` value. Unrecognized fields are ignored.'
    );
    req.throwOn(401, ErrorEnvelopeError, 'Invalid or missing API key.');
    req.throwOn(402, ErrorEnvelopeError, 'Insufficient credits.');
    req.throwOn(429, ErrorEnvelopeError, 'Rate limited.');
    req.throwOn(500, ErrorEnvelopeError, 'Unexpected server error.');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(fetchResponseSchema, requestOptions);
  }
}
