/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CreateMonitorRequest,
  createMonitorRequestSchema,
} from '../models/createMonitorRequest.js';
import {
  CreateMonitorResponse,
  createMonitorResponseSchema,
} from '../models/createMonitorResponse.js';
import {
  GetMonitorResponse,
  getMonitorResponseSchema,
} from '../models/getMonitorResponse.js';
import {
  ListMonitorsResponse,
  listMonitorsResponseSchema,
} from '../models/listMonitorsResponse.js';
import {
  UpdateMonitorRequest,
  updateMonitorRequestSchema,
} from '../models/updateMonitorRequest.js';
import {
  UpdateMonitorResponse,
  updateMonitorResponseSchema,
} from '../models/updateMonitorResponse.js';
import { nullable, number, optional, string, unknown } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ErrorEnvelopeError } from '../errors/errorEnvelopeError.js';

export class MonitorsApi extends BaseApi {
  /**
   * @param name   Matches a monitor whose name is exactly this.
   * @param status One of `active`, `paused`, `disabled`. `deleted` is not a filter: a deleted
   *                                monitor is invisible.
   * @param since  Exclusive lower bound: the `monitor_id` of a monitor to start after.
   * @param before Exclusive upper bound. The list is newest first, so page forward with the
   *                                `monitor_id` of the last monitor on the previous page.
   * @param limit  Defaults to 100, at most 1,000. A short page is normal: a page ends at `limit` or
   *                                at the byte budget, whichever binds first.
   * @return Response from the API call
   */
  async listMonitors(
    name?: string | null,
    status?: string | null,
    since?: string | null,
    before?: string | null,
    limit?: number | null,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListMonitorsResponse>> {
    const req = this.createRequest('GET', '/v1/monitors');
    const mapped = req.prepareArgs({
      name: [name, optional(nullable(string()))],
      status: [status, optional(nullable(string()))],
      since: [since, optional(nullable(string()))],
      before: [before, optional(nullable(string()))],
      limit: [limit, optional(nullable(number()))],
    });
    req.query('name', mapped.name);
    req.query('status', mapped.status);
    req.query('since', mapped.since);
    req.query('before', mapped.before);
    req.query('limit', mapped.limit);
    req.throwOn(401, ErrorEnvelopeError, 'Invalid or missing API key.');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(listMonitorsResponseSchema, requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async createMonitor(
    body: CreateMonitorRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreateMonitorResponse>> {
    const req = this.createRequest('POST', '/v1/monitors');
    const mapped = req.prepareArgs({
      body: [body, createMonitorRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ErrorEnvelopeError, 'Missing or malformed fields.');
    req.throwOn(401, ErrorEnvelopeError, 'Invalid or missing API key.');
    req.throwOn(
      409,
      ErrorEnvelopeError,
      'That name is already taken in this org.'
    );
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(createMonitorResponseSchema, requestOptions);
  }

  /**
   * @param monitorId
   * @return Response from the API call
   */
  async getMonitor(
    monitorId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetMonitorResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({ monitorId: [monitorId, string()] });
    req.appendTemplatePath`/v1/monitors/${mapped.monitorId}`;
    req.throwOn(404, ErrorEnvelopeError, 'No such monitor in this org.');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(getMonitorResponseSchema, requestOptions);
  }

  /**
   * @param monitorId
   * @return Response from the API call
   */
  async deleteMonitor(
    monitorId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<unknown | undefined>> {
    const req = this.createRequest('DELETE');
    const mapped = req.prepareArgs({ monitorId: [monitorId, string()] });
    req.appendTemplatePath`/v1/monitors/${mapped.monitorId}`;
    req.throwOn(404, ErrorEnvelopeError, 'No such monitor in this org.');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(optional(unknown()), requestOptions);
  }

  /**
   * @param monitorId
   * @param body
   * @return Response from the API call
   */
  async updateMonitor(
    monitorId: string,
    body: UpdateMonitorRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UpdateMonitorResponse>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      monitorId: [monitorId, string()],
      body: [body, updateMonitorRequestSchema],
    });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/v1/monitors/${mapped.monitorId}`;
    req.throwOn(404, ErrorEnvelopeError, 'No such monitor in this org.');
    req.throwOn(
      409,
      ErrorEnvelopeError,
      'That name is already taken in this org.'
    );
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(updateMonitorResponseSchema, requestOptions);
  }
}
