/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ListRecordsResponse,
  listRecordsResponseSchema,
} from '../models/listRecordsResponse.js';
import {
  ListRunRecordsResponse,
  listRunRecordsResponseSchema,
} from '../models/listRunRecordsResponse.js';
import { boolean, nullable, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ErrorEnvelopeError } from '../errors/errorEnvelopeError.js';

export class RecordsApi extends BaseApi {
  /**
   * @param monitorId
   * @param since           Exclusive lower bound on `record_id`.
   * @param before          Exclusive upper bound on `record_id`.
   * @param limit           Defaults to 100, at most 1,000. A short page is normal: a page ends at
   *                                          `limit` or at the byte budget, whichever binds first.
   * @param includeContent  Include each record's document content. Defaults to true.
   * @return Response from the API call
   */
  async listRecords(
    monitorId: string,
    since?: string | null,
    before?: string | null,
    limit?: number | null,
    includeContent?: boolean | null,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListRecordsResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      monitorId: [monitorId, string()],
      since: [since, optional(nullable(string()))],
      before: [before, optional(nullable(string()))],
      limit: [limit, optional(nullable(number()))],
      includeContent: [includeContent, optional(nullable(boolean()))],
    });
    req.query('since', mapped.since);
    req.query('before', mapped.before);
    req.query('limit', mapped.limit);
    req.query('include_content', mapped.includeContent);
    req.appendTemplatePath`/v1/monitors/${mapped.monitorId}/records`;
    req.throwOn(404, ErrorEnvelopeError, 'No such monitor in this org.');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(listRecordsResponseSchema, requestOptions);
  }

  /**
   * Exists so that no consumer does arithmetic on a record id: a webhook carries a run's record range as
   * a bound, not a dense sequence.
   *
   * @param monitorId
   * @param runId
   * @param since           Exclusive lower bound on `record_id`.
   * @param before          Exclusive upper bound on `record_id`.
   * @param limit           Defaults to 100, at most 1,000. A short page is normal: a page ends at
   *                                          `limit` or at the byte budget, whichever binds first.
   * @param includeContent  Include each record's document content. Defaults to true.
   * @return Response from the API call
   */
  async listRunRecords(
    monitorId: string,
    runId: string,
    since?: string | null,
    before?: string | null,
    limit?: number | null,
    includeContent?: boolean | null,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListRunRecordsResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      monitorId: [monitorId, string()],
      runId: [runId, string()],
      since: [since, optional(nullable(string()))],
      before: [before, optional(nullable(string()))],
      limit: [limit, optional(nullable(number()))],
      includeContent: [includeContent, optional(nullable(boolean()))],
    });
    req.query('since', mapped.since);
    req.query('before', mapped.before);
    req.query('limit', mapped.limit);
    req.query('include_content', mapped.includeContent);
    req.appendTemplatePath`/v1/monitors/${mapped.monitorId}/runs/${mapped.runId}/records`;
    req.throwOn(404, ErrorEnvelopeError, 'No such run on this monitor.');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(listRunRecordsResponseSchema, requestOptions);
  }
}
