/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  GetRunResponse,
  getRunResponseSchema,
} from '../models/getRunResponse.js';
import {
  ListRunRequestsResponse,
  listRunRequestsResponseSchema,
} from '../models/listRunRequestsResponse.js';
import {
  ListRunsResponse,
  listRunsResponseSchema,
} from '../models/listRunsResponse.js';
import { nullable, number, optional, string } from '../schema.js';
import { BaseApi } from './baseApi.js';
import { ErrorEnvelopeError } from '../errors/errorEnvelopeError.js';

export class RunsApi extends BaseApi {
  /**
   * @param monitorId
   * @param since      Exclusive lower bound on `run_id`.
   * @param before     Exclusive upper bound on `run_id`.
   * @param limit      Defaults to 100, at most 1,000.
   * @param sort       `desc` (the default, newest first) or `asc`.
   * @return Response from the API call
   */
  async listRuns(
    monitorId: string,
    since?: string | null,
    before?: string | null,
    limit?: number | null,
    sort?: string | null,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListRunsResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      monitorId: [monitorId, string()],
      since: [since, optional(nullable(string()))],
      before: [before, optional(nullable(string()))],
      limit: [limit, optional(nullable(number()))],
      sort: [sort, optional(nullable(string()))],
    });
    req.query('since', mapped.since);
    req.query('before', mapped.before);
    req.query('limit', mapped.limit);
    req.query('sort', mapped.sort);
    req.appendTemplatePath`/v1/monitors/${mapped.monitorId}/runs`;
    req.throwOn(404, ErrorEnvelopeError, 'No such monitor in this org.');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(listRunsResponseSchema, requestOptions);
  }

  /**
   * @param monitorId
   * @param runId
   * @return Response from the API call
   */
  async getRun(
    monitorId: string,
    runId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<GetRunResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      monitorId: [monitorId, string()],
      runId: [runId, string()],
    });
    req.appendTemplatePath`/v1/monitors/${mapped.monitorId}/runs/${mapped.runId}`;
    req.throwOn(404, ErrorEnvelopeError, 'No such run on this monitor.');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(getRunResponseSchema, requestOptions);
  }

  /**
   * The only place a customer can tell *this query failed* from *there was genuinely nothing new*:
   * records are a stream of positives, and absence cannot be inferred from presences.
   *
   * @param monitorId
   * @param runId
   * @return Response from the API call
   */
  async listRunRequests(
    monitorId: string,
    runId: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<ListRunRequestsResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      monitorId: [monitorId, string()],
      runId: [runId, string()],
    });
    req.appendTemplatePath`/v1/monitors/${mapped.monitorId}/runs/${mapped.runId}/requests`;
    req.throwOn(404, ErrorEnvelopeError, 'No such run on this monitor.');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(listRunRequestsResponseSchema, requestOptions);
  }
}
