/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { SearchRequest, searchRequestSchema } from '../models/searchRequest.js';
import {
  SearchResponse,
  searchResponseSchema,
} from '../models/searchResponse.js';
import { BaseApi } from './baseApi.js';
import { ErrorEnvelopeError } from '../errors/errorEnvelopeError.js';

export class SearchApi extends BaseApi {
  /**
   * @param body
   * @return Response from the API call
   */
  async search(
    body: SearchRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<SearchResponse>> {
    const req = this.createRequest('POST', '/v1/search');
    const mapped = req.prepareArgs({ body: [body, searchRequestSchema] });
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(
      400,
      ErrorEnvelopeError,
      'Missing or malformed request fields.'
    );
    req.throwOn(401, ErrorEnvelopeError, 'Invalid or missing API key.');
    req.throwOn(402, ErrorEnvelopeError, 'Insufficient credits.');
    req.throwOn(
      404,
      ErrorEnvelopeError,
      'Endpoint not found, or a scope that matches nothing.'
    );
    req.throwOn(405, ErrorEnvelopeError, 'Wrong method for this endpoint.');
    req.throwOn(413, ErrorEnvelopeError, 'Request body is too large.');
    req.throwOn(
      429,
      ErrorEnvelopeError,
      'Rate limit exceeded. Wait before retrying.'
    );
    req.throwOn(500, ErrorEnvelopeError, 'Unexpected server error.');
    req.authenticate([{ apiKeyAuth: true }]);
    return req.callAsJson(searchResponseSchema, requestOptions);
  }
}
