/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AgentRunCitation,
  agentRunCitationSchema,
} from './agentRunCitation.js';

/** Citations for one field of `output.structured`. */
export interface AgentRunGrounding {
  /** Citations supporting this field's value. */
  citations?: AgentRunCitation[];
  /** Dot-notation path into the structured output, e.g. "companies.0.ceo". */
  field?: string;
  additionalProperties?: Record<string, unknown>;
}

export const agentRunGroundingSchema: Schema<AgentRunGrounding> = lazy(() =>
  typedExpandoObject(
    {
      citations: ['citations', optional(array(agentRunCitationSchema))],
      field: ['field', optional(string())],
    },
    'additionalProperties',
    optional(unknown())
  )
);
