/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AgentRunGrounding,
  agentRunGroundingSchema,
} from './agentRunGrounding.js';
import { AgentRunSource, agentRunSourceSchema } from './agentRunSource.js';

/** A run's output. */
export interface AgentRunOutput {
  /**
   * Per-field citations for `structured`. Empty when there is no structured
   * output.
   */
  grounding?: AgentRunGrounding[];
  /**
   * The sources cited by `text` or `grounding`, numbered in order of first
   * citation.
   */
  sources?: AgentRunSource[];
  /**
   * Structured result shaped by the request's `output_schema`. Unset when the
   * request had none. Fields that could not be grounded are expected to be
   * null. On gRPC the object is JSON-encoded.
   */
  structured?: unknown | null;
  /**
   * Cited markdown report. Inline `\[n\]` markers cite the entry of `sources`
   * whose `id` is `n`.
   */
  text?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const agentRunOutputSchema: Schema<AgentRunOutput> = lazy(() =>
  typedExpandoObject(
    {
      grounding: ['grounding', optional(array(agentRunGroundingSchema))],
      sources: ['sources', optional(array(agentRunSourceSchema))],
      structured: ['structured', optional(nullable(unknown()))],
      text: ['text', optional(nullable(string()))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
