/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { AgentRunOutput2, agentRunOutput2Schema } from './agentRunOutput2.js';
import {
  AgentRunRequest2,
  agentRunRequest2Schema,
} from './agentRunRequest2.js';
import { AgentRunStatus2, agentRunStatus2Schema } from './agentRunStatus2.js';
import {
  AgentRunStopReason2,
  agentRunStopReason2Schema,
} from './agentRunStopReason2.js';

/** An agent run. */
export interface AgentRun {
  /** When the run reached a terminal state. Unset until then. */
  completedAt?: string | null;
  /** When the run was created, as an ISO 8601 timestamp. */
  createdAt?: string;
  /** Unique run id. */
  id?: string;
  /** Object type, always "agent.run". */
  object?: string;
  output?: AgentRunOutput2 | null;
  request?: AgentRunRequest2 | null;
  /** When the run started. Unset while pending. */
  startedAt?: string | null;
  status?: AgentRunStatus2;
  stopReason?: AgentRunStopReason2 | null;
  additionalProperties?: Record<string, unknown>;
}

export const agentRunSchema: Schema<AgentRun> = lazy(() =>
  typedExpandoObject(
    {
      completedAt: ['completed_at', optional(nullable(string()))],
      createdAt: ['created_at', optional(string())],
      id: ['id', optional(string())],
      object: ['object', optional(string())],
      output: ['output', optional(nullable(agentRunOutput2Schema))],
      request: ['request', optional(nullable(agentRunRequest2Schema))],
      startedAt: ['started_at', optional(nullable(string()))],
      status: ['status', optional(agentRunStatus2Schema)],
      stopReason: [
        'stop_reason',
        optional(nullable(agentRunStopReason2Schema)),
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
