/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** One citation supporting a grounded field. */
export interface AgentRunCitation {
  /** `id` of the entry in `sources` this citation points at. */
  sourceId?: number;
  /** URL of the cited document. */
  url?: string;
  additionalProperties?: Record<string, unknown>;
}

export const agentRunCitationSchema: Schema<AgentRunCitation> = typedExpandoObject(
  {
    sourceId: ['source_id', optional(number())],
    url: ['url', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
