/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** One source a run cited. */
export interface AgentRunSource {
  /**
   * Identifier within the run, cited as `\[id\]` in `text` and as `source_id`
   * in `grounding`.
   */
  id?: number;
  /** URL of the source document. */
  url?: string;
  additionalProperties?: Record<string, unknown>;
}

export const agentRunSourceSchema: Schema<AgentRunSource> = typedExpandoObject(
  { id: ['id', optional(number())], url: ['url', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
