/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AgentRunStopReason2
 */
export enum AgentRunStopReason2 {
  Finished = 'finished',
  BudgetReached = 'budget_reached',
  Timeout = 'timeout',
  Cancelled = 'cancelled',
  InvalidOutput = 'invalid_output',
  InternalError = 'internal_error',
}

/**
 * Schema for AgentRunStopReason2
 */
export const agentRunStopReason2Schema: Schema<AgentRunStopReason2> = stringEnum(
  AgentRunStopReason2
);
