/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AgentRunStatus2
 */
export enum AgentRunStatus2 {
  Pending = 'pending',
  Running = 'running',
  Completed = 'completed',
  Failed = 'failed',
  Cancelled = 'cancelled',
}

/**
 * Schema for AgentRunStatus2
 */
export const agentRunStatus2Schema: Schema<AgentRunStatus2> = stringEnum(
  AgentRunStatus2
);
