/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** The request a run was created with. */
export interface AgentRunRequest {
  /**
   * The effort level the run executes at: the request's `effort`, or the
   * default level when it named none.
   */
  effort?: string | null;
  /**
   * The request's `output_schema`, when one was given. On gRPC the object is
   * JSON-encoded.
   */
  outputSchema?: unknown | null;
  /** The natural-language question. */
  query?: string;
  additionalProperties?: Record<string, unknown>;
}

export const agentRunRequestSchema: Schema<AgentRunRequest> = typedExpandoObject(
  {
    effort: ['effort', optional(nullable(string()))],
    outputSchema: ['output_schema', optional(nullable(unknown()))],
    query: ['query', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
