/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AgentRunStatus
 */
export enum AgentRunStatus {
  Pending = 'pending',
  Running = 'running',
  Completed = 'completed',
  Failed = 'failed',
  Cancelled = 'cancelled',
}

/**
 * Schema for AgentRunStatus
 */
export const agentRunStatusSchema: Schema<AgentRunStatus> = stringEnum(
  AgentRunStatus
);
