/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { HttpCitation, httpCitationSchema } from './httpCitation.js';

/** Buffered JSON response body for `POST /v1/answer`. */
export interface AnswerHttpResponse {
  /**
   * Markdown answer text. Inline citations follow the form
   * `text ([Source Name](url))`.
   */
  answer: string;
  /**
   * The sources the answer was grounded in. Every source the answer was
   * given is returned, whether or not the text cites it.
   */
  citations: HttpCitation[];
  additionalProperties?: Record<string, unknown>;
}

export const answerHttpResponseSchema: Schema<AnswerHttpResponse> = lazy(() =>
  typedExpandoObject(
    {
      answer: ['answer', string()],
      citations: ['citations', array(httpCitationSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
