/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** JSON request body for `POST /v1/answer`. */
export interface AnswerHttpRequest {
  /**
   * API key. Either this or the `x-api-key` header must be supplied;
   * the header takes precedence.
   */
  apiKey?: string | null;
  /** When true, citations carry the document content text. Default false. */
  includeContent?: boolean;
  /**
   * Selects the answer tier, which determines behavior and billing.
   * Omitted resolves to the default tier. Independent of `scope`; the
   * response shape is unchanged.
   */
  model?: string | null;
  /** The natural-language question. */
  query: string;
  /**
   * Optional `OpenAI` `response_format` object (`{"type": "text" |
   * "json_object" | "json_schema", ...}`), accepted as raw JSON exactly
   * like `/v1/chat/completions`. Under a structured type no inline
   * citations are added, so the answer stays schema-valid; a malformed
   * value is a `400` before billing. Omitted leaves the answer as Markdown
   * prose.
   * Applies at every tier.
   */
  responseFormat?: unknown;
  /**
   * Restricts the grounding search to one scope.
   * Currently available:
   * - `news`
   * - `wikipedia`
   * - `people`
   * - `companies`
   * Omitted, empty or whitespace-only searches the default scope.
   */
  scope?: string | null;
  /** When true, stream the answer as OpenAI-mimic SSE chunks. Default false. */
  stream?: boolean;
  /**
   * Steers how the answer is presented — tone, voice, format. It is
   * subordinate to the grounding and citation rules, which stay in force.
   * That precedence is instructional, not a sandbox. Omitted, empty or
   * whitespace-only leaves the presentation unchanged. Applies at every
   * tier and composes with `response_format`. At most 8 KiB of UTF-8; a
   * longer value is a `400` before billing.
   */
  systemPrompt?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const answerHttpRequestSchema: Schema<AnswerHttpRequest> = typedExpandoObject(
  {
    apiKey: ['api_key', optional(nullable(string()))],
    includeContent: ['include_content', optional(boolean())],
    model: ['model', optional(nullable(string()))],
    query: ['query', string()],
    responseFormat: ['response_format', optional(unknown())],
    scope: ['scope', optional(nullable(string()))],
    stream: ['stream', optional(boolean())],
    systemPrompt: ['system_prompt', optional(nullable(string()))],
  },
  'additionalProperties',
  optional(unknown())
);
