/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/**
 * The ceiling on the content returned.
 * The ceiling is an upper bound; the response carries at most what is specified here.
 * The service may hold callers to a tighter bound than the range below. A larger
 * request is then served at that bound rather than refused, which still carries at
 * most what was specified. Only a value outside the range below is rejected.
 */
export interface ContentOptions {
  /**
   * Ceiling on the characters of any single result's content.
   * Counts Unicode code points -- Rust `char`, Python `len(s)`, JavaScript `\[...s\].length`.
   * Defaults to 20000, accepted range 100-1000000.
   */
  maxCharactersPerResult?: number | null;
  additionalProperties?: Record<string, unknown>;
}

export const contentOptionsSchema: Schema<ContentOptions> = typedExpandoObject(
  {
    maxCharactersPerResult: [
      'max_characters_per_result',
      optional(nullable(number())),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
