/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  object,
  optional,
  Schema,
  string,
  unknown,
} from '../schema.js';

export interface CreateAgentRunRequest {
  /** The API key, on gRPC requests. REST reads the `x-api-key` header instead. */
  apiKey?: string | null;
  /**
   * Effort level: how much research the run may do, and its price. One of
   * the configured level names (e.g. `low`, `medium`, `high`, `max`).
   * Omitted = the default level.
   */
  effort?: string | null;
  /**
   * Optional OpenAI-style `response_format` object requesting structured
   * output: `{"type": "text" | "json_object" | "json_schema", ...}`, with
   * `name` / `schema` / `strict` for type `json_schema`. A structured type
   * adds `output.structured` and its `grounding` alongside the cited text;
   * type `text` is accepted and requests no structure. On gRPC the object is
   * JSON-encoded.
   */
  outputSchema?: unknown | null;
  /**
   * The natural-language question. Instructions inside the query are
   * followed.
   */
  query?: string;
}

export const createAgentRunRequestSchema: Schema<CreateAgentRunRequest> = object(
  {
    apiKey: ['api_key', optional(nullable(string()))],
    effort: ['effort', optional(nullable(string()))],
    outputSchema: ['output_schema', optional(nullable(unknown()))],
    query: ['query', optional(string())],
  }
);
