/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { MonitorStatus2, monitorStatus2Schema } from './monitorStatus2.js';
import { SearchRequest, searchRequestSchema } from './searchRequest.js';
import { Webhook, webhookSchema } from './webhook.js';

export interface CreateMonitorRequest {
  cadence: string;
  apiKey?: string | null;
  /**
   * Unique per org among live monitors; a deleted monitor's name becomes
   * available again. At most 512 bytes of UTF-8.
   */
  name?: string;
  /**
   * At least one, at most 1000. Every request runs on every run. A request
   * with an `api_key` set, a blank `query`, or a body identical to another in
   * the list is rejected.
   */
  searchRequests?: SearchRequest[];
  status?: MonitorStatus2;
  webhook?: Webhook | null;
  additionalProperties?: Record<string, unknown>;
}

export const createMonitorRequestSchema: Schema<CreateMonitorRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        cadence: ['cadence', string()],
        apiKey: ['api_key', optional(nullable(string()))],
        name: ['name', optional(string())],
        searchRequests: [
          'search_requests',
          optional(array(searchRequestSchema)),
        ],
        status: ['status', optional(monitorStatus2Schema)],
        webhook: ['webhook', optional(nullable(webhookSchema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
