/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Monitor, monitorSchema } from './monitor.js';

export interface CreateMonitorResponse {
  monitor?: Monitor | null;
  /**
   * Returned once, at create, and never again. Issued whether or not the
   * create supplied a webhook, so keep it.
   */
  webhookSecret?: string;
  additionalProperties?: Record<string, unknown>;
}

export const createMonitorResponseSchema: Schema<CreateMonitorResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        monitor: ['monitor', optional(nullable(monitorSchema))],
        webhookSecret: ['webhook_secret', optional(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
