/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Snippet, snippetSchema } from './snippet.js';

/**
 * A single search result.
 * `url` and `published_date` are returned without being asked for, and either
 * may still be absent for a document that carries no such value. The remaining
 * members are populated only when `SearchRequest.fields` asked for them.
 */
export interface Document {
  content?: string | null;
  /** Publication date as ISO 8601 string (e.g. "2024-03-15T00:00:00Z") */
  publishedDate?: string | null;
  /**
   * The document's highest-scoring snippets, in the order they appear in the document.
   * Populated when `fields.snippets` is selected and passages are available;
   * empty otherwise.
   */
  snippets?: Snippet[];
  url?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const documentSchema: Schema<Document> = lazy(() =>
  typedExpandoObject(
    {
      content: ['content', optional(nullable(string()))],
      publishedDate: ['published_date', optional(nullable(string()))],
      snippets: ['snippets', optional(array(snippetSchema))],
      url: ['url', optional(nullable(string()))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
