/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** The error context. */
export interface EnvelopeError1 {
  /** The error code. */
  code: string;
  /** The error message. */
  message: string;
  additionalProperties?: Record<string, unknown>;
}

export const envelopeError1Schema: Schema<EnvelopeError1> = typedExpandoObject(
  { code: ['code', string()], message: ['message', string()] },
  'additionalProperties',
  optional(unknown())
);
