/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/**
 * The error context. `code` is a stable descriptor in all-caps from a closed
 * set per endpoint. `message` is a human-readable summary of what went wrong.
 */
export interface EnvelopeError {
  /** The error code. */
  code: string;
  /** The error message. */
  message: string;
  additionalProperties?: Record<string, unknown>;
}

export const envelopeErrorSchema: Schema<EnvelopeError> = typedExpandoObject(
  { code: ['code', string()], message: ['message', string()] },
  'additionalProperties',
  optional(unknown())
);
