/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for FetchStatus2
 */
export enum FetchStatus2 {
  Ok = 'ok',
  Error = 'error',
}

/**
 * Schema for FetchStatus2
 */
export const fetchStatus2Schema: Schema<FetchStatus2> = stringEnum(
  FetchStatus2
);
