/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { FetchResult, fetchResultSchema } from './fetchResult.js';

/** One result per requested URL. */
export interface FetchResponse {
  /**
   * One entry per entry in `FetchRequest.urls`, successful or not, in the order
   * the URLs were requested.
   * Correlate on `FetchResult.requested_url` rather than on position.
   */
  results?: FetchResult[];
  additionalProperties?: Record<string, unknown>;
}

export const fetchResponseSchema: Schema<FetchResponse> = lazy(() =>
  typedExpandoObject(
    { results: ['results', optional(array(fetchResultSchema))] },
    'additionalProperties',
    optional(unknown())
  )
);
