/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  nullable,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { FetchError1, fetchError1Schema } from './fetchError1.js';
import { FetchStatus2, fetchStatus2Schema } from './fetchStatus2.js';

/** The outcome for one URL. */
export interface FetchResult {
  /**
   * The origin's declared media type for the main document, without
   * parameters.
   * Frequently unset, including on results that carry content. Never branch on
   * it: `status` says whether a result carries content.
   */
  contentType?: string | null;
  error?: FetchError1 | null;
  fetchedAt?: string | null;
  /**
   * The URL the content actually came from, after HTTP redirects and any
   * client-side navigation. Equal to `requested_url` when nothing redirected.
   * Set on a result whose `status` is ERROR only when the failure happened
   * after the origin answered, such as a page this service could not extract.
   * Unset when the URL was never reached.
   */
  finalUrl?: string | null;
  /**
   * The origin's HTTP status code for the main document. Unset when no network
   * response was observed for the navigation.
   * An HTTP error status is not a fetch failure: this service renders the
   * origin's error page, so a 404 arrives as an OK result carrying 404. On a
   * result whose `status` is ERROR, this follows `final_url` - set only when
   * the failure happened after the origin answered.
   */
  httpStatusCode?: number | null;
  /** The page's main content as Markdown, with boilerplate removed. */
  markdown?: string | null;
  /**
   * The URL this answers, echoed verbatim from the request -- byte for byte,
   * never normalized, and never the post-redirect URL. This is the correlation
   * key. Where redirects landed is `final_url`.
   */
  requestedUrl?: string;
  status: FetchStatus2;
  additionalProperties?: Record<string, unknown>;
}

export const fetchResultSchema: Schema<FetchResult> = lazy(() =>
  typedExpandoObject(
    {
      contentType: ['content_type', optional(nullable(string()))],
      error: ['error', optional(nullable(fetchError1Schema))],
      fetchedAt: ['fetched_at', optional(nullable(string()))],
      finalUrl: ['final_url', optional(nullable(string()))],
      httpStatusCode: ['http_status_code', optional(nullable(number()))],
      markdown: ['markdown', optional(nullable(string()))],
      requestedUrl: ['requested_url', optional(string())],
      status: ['status', fetchStatus2Schema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
