/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for FetchStatus
 */
export enum FetchStatus {
  Ok = 'ok',
  Error = 'error',
}

/**
 * Schema for FetchStatus
 */
export const fetchStatusSchema: Schema<FetchStatus> = stringEnum(FetchStatus);
