/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  FieldsContent,
  fieldsContentSchema,
} from './containers/fieldsContent.js';
import {
  FieldsSnippets,
  fieldsSnippetsSchema,
} from './containers/fieldsSnippets.js';

/**
 * The selectable members of a response `Document`, and how much of each to return.
 * `Document.url` and `Document.published_date` are always selected.
 * Each member takes `true`, `false`, or an object of ceilings. An object selects the member and
 * bounds it, so `{"content": {"max_characters_per_result": 500}}` returns content and no
 * snippets. `{"content": true}` selects content under the default ceiling, which is what
 * `{"content": {}}` returns as well. `false` switches the member off.
 * A `fields` that names neither member returns the defaults below, so `{}` and a wholly absent
 * `fields` mean the same thing. A `fields` that names either is read literally, so
 * `{"snippets": true}` returns passages and no content.
 */
export interface Fields {
  /** Emit `Document.content`. Unset is true. */
  content?: FieldsContent;
  /** Emit `Document.snippets`. Unset is false. */
  snippets?: FieldsSnippets;
  additionalProperties?: Record<string, unknown>;
}

export const fieldsSchema: Schema<Fields> = lazy(() =>
  typedExpandoObject(
    {
      content: ['content', optional(fieldsContentSchema)],
      snippets: ['snippets', optional(fieldsSnippetsSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
