/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  Fields2Content,
  fields2ContentSchema,
} from './containers/fields2Content.js';
import {
  Fields2Snippets,
  fields2SnippetsSchema,
} from './containers/fields2Snippets.js';

/**
 * Which selectable members of `Document` to populate.
 * If absent, defaults to `{content: true}`, which returns content under the
 * default ceiling stated on `ContentOptions`.
 */
export interface Fields2 {
  /** Emit `Document.content`. Unset is true. */
  content?: Fields2Content;
  /** Emit `Document.snippets`. Unset is false. */
  snippets?: Fields2Snippets;
  additionalProperties?: Record<string, unknown>;
}

export const fields2Schema: Schema<Fields2> = lazy(() =>
  typedExpandoObject(
    {
      content: ['content', optional(fields2ContentSchema)],
      snippets: ['snippets', optional(fields2SnippetsSchema)],
    },
    'additionalProperties',
    optional(unknown())
  )
);
