/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  nullable,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Monitor, monitorSchema } from './monitor.js';
import { RunState2, runState2Schema } from './runState2.js';

export interface GetMonitorResponse {
  monitor?: Monitor | null;
  runState: RunState2;
  additionalProperties?: Record<string, unknown>;
}

export const getMonitorResponseSchema: Schema<GetMonitorResponse> = lazy(() =>
  typedExpandoObject(
    {
      monitor: ['monitor', optional(nullable(monitorSchema))],
      runState: ['run_state', runState2Schema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
