/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  nullable,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Run, runSchema } from './run.js';

export interface GetRunResponse {
  run?: Run | null;
  additionalProperties?: Record<string, unknown>;
}

export const getRunResponseSchema: Schema<GetRunResponse> = lazy(() =>
  typedExpandoObject(
    { run: ['run', optional(nullable(runSchema))] },
    'additionalProperties',
    optional(unknown())
  )
);
