/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** HTTP-shape citation. Mirrors the `Citation` proto. */
export interface HttpCitation {
  /** Document content text (only when `include_content = true`). */
  content?: string | null;
  /** URL of the source document. */
  url: string;
  additionalProperties?: Record<string, unknown>;
}

export const httpCitationSchema: Schema<HttpCitation> = typedExpandoObject(
  {
    content: ['content', optional(nullable(string()))],
    url: ['url', string()],
  },
  'additionalProperties',
  optional(unknown())
);
