/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { AgentRun, agentRunSchema } from './agentRun.js';

/** List-runs response: one page of runs. */
export interface ListAgentRunsResponse {
  /** Cursor to the next page. Unset on the last page. */
  next?: string | null;
  /** The page's runs, newest first. */
  runs?: AgentRun[];
  additionalProperties?: Record<string, unknown>;
}

export const listAgentRunsResponseSchema: Schema<ListAgentRunsResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        next: ['next', optional(nullable(string()))],
        runs: ['runs', optional(array(agentRunSchema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
