/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Record, recordSchema } from './record.js';

export interface ListRecordsResponse {
  /**
   * True when limit or the byte budget cut the page short. Page forward with
   * since = records\[last\].record_id.
   */
  hasMore?: boolean;
  /**
   * Oldest first. A short page is normal: a page ends at limit or at a byte
   * budget, whichever binds first.
   */
  records?: Record[];
  additionalProperties?: Record<string, unknown>;
}

export const listRecordsResponseSchema: Schema<ListRecordsResponse> = lazy(() =>
  typedExpandoObject(
    {
      hasMore: ['has_more', optional(boolean())],
      records: ['records', optional(array(recordSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
