/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { RunRequest, runRequestSchema } from './runRequest.js';

export interface ListRunRequestsResponse {
  /** Ordered by request_id. */
  requests?: RunRequest[];
  additionalProperties?: Record<string, unknown>;
}

export const listRunRequestsResponseSchema: Schema<ListRunRequestsResponse> = lazy(
  () =>
    typedExpandoObject(
      { requests: ['requests', optional(array(runRequestSchema))] },
      'additionalProperties',
      optional(unknown())
    )
);
