/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Monitor, monitorSchema } from './monitor.js';

export interface ListMonitorsResponse {
  /**
   * True when limit or the byte budget cut the page short. Page forward with
   * before = monitors\[last\].monitor_id.
   */
  hasMore?: boolean;
  /**
   * Newest first. A short page is normal: a page ends at limit or at a byte
   * budget, whichever binds first. A monitor carries its whole request list,
   * so a count alone cannot bound the response.
   */
  monitors?: Monitor[];
  additionalProperties?: Record<string, unknown>;
}

export const listMonitorsResponseSchema: Schema<ListMonitorsResponse> = lazy(
  () =>
    typedExpandoObject(
      {
        hasMore: ['has_more', optional(boolean())],
        monitors: ['monitors', optional(array(monitorSchema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
