/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Run, runSchema } from './run.js';

export interface ListRunsResponse {
  /** True when limit cut the page short. */
  hasMore?: boolean;
  /**
   * Newest first by default, so \[0\] is the latest run. Page back with
   * before = runs\[last\].run_id; pass sort = SORT_ORDER_ASC to walk forward
   * instead, and page with since = runs\[last\].run_id.
   */
  runs?: Run[];
  additionalProperties?: Record<string, unknown>;
}

export const listRunsResponseSchema: Schema<ListRunsResponse> = lazy(() =>
  typedExpandoObject(
    {
      hasMore: ['has_more', optional(boolean())],
      runs: ['runs', optional(array(runSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
