/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for MonitorStatus
 */
export enum MonitorStatus {
  Active = 'active',
  Paused = 'paused',
  Disabled = 'disabled',
  Deleted = 'deleted',
}

/**
 * Schema for MonitorStatus
 */
export const monitorStatusSchema: Schema<MonitorStatus> = stringEnum(
  MonitorStatus
);
