/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  MonitorSearchRequest,
  monitorSearchRequestSchema,
} from './monitorSearchRequest.js';
import { MonitorStatus, monitorStatusSchema } from './monitorStatus.js';
import { Webhook, webhookSchema } from './webhook.js';

export interface Monitor {
  cadence: string;
  createdAt?: string | null;
  monitorId?: string;
  name?: string;
  searchRequests?: MonitorSearchRequest[];
  status: MonitorStatus;
  updatedAt?: string | null;
  webhook?: Webhook | null;
  additionalProperties?: Record<string, unknown>;
}

export const monitorSchema: Schema<Monitor> = lazy(() =>
  typedExpandoObject(
    {
      cadence: ['cadence', string()],
      createdAt: ['created_at', optional(nullable(string()))],
      monitorId: ['monitor_id', optional(string())],
      name: ['name', optional(string())],
      searchRequests: [
        'search_requests',
        optional(array(monitorSearchRequestSchema)),
      ],
      status: ['status', monitorStatusSchema],
      updatedAt: ['updated_at', optional(nullable(string()))],
      webhook: ['webhook', optional(nullable(webhookSchema))],
    },
    'additionalProperties',
    optional(unknown())
  )
);
