/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for MonitorStatus2
 */
export enum MonitorStatus2 {
  Active = 'active',
  Paused = 'paused',
  Disabled = 'disabled',
  Deleted = 'deleted',
}

/**
 * Schema for MonitorStatus2
 */
export const monitorStatus2Schema: Schema<MonitorStatus2> = stringEnum(
  MonitorStatus2
);
