/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { SearchRequest, searchRequestSchema } from './searchRequest.js';

/** A search request stored on a monitor, with its server-assigned id. */
export interface MonitorSearchRequest {
  /** Consecutive failed runs for this request. */
  consecutiveFailures?: bigint;
  lastSuccessAt?: string | null;
  request?: SearchRequest | null;
  requestId?: string;
  additionalProperties?: Record<string, unknown>;
}

export const monitorSearchRequestSchema: Schema<MonitorSearchRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        consecutiveFailures: ['consecutive_failures', optional(bigint())],
        lastSuccessAt: ['last_success_at', optional(nullable(string()))],
        request: ['request', optional(nullable(searchRequestSchema))],
        requestId: ['request_id', optional(string())],
      },
      'additionalProperties',
      optional(unknown())
    )
);
