/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { SearchRecord, searchRecordSchema } from './searchRecord.js';

export interface Payload {
  searchResult: SearchRecord;
  additionalProperties?: Record<string, unknown>;
}

export const payloadSchema: Schema<Payload> = lazy(() =>
  typedExpandoObject(
    { searchResult: ['search_result', searchRecordSchema] },
    'additionalProperties',
    optional(unknown())
  )
);
