/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for RecordType
 */
export enum RecordType {
  SearchResult = 'search_result',
}

/**
 * Schema for RecordType
 */
export const recordTypeSchema: Schema<RecordType> = stringEnum(RecordType);
