/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { RecordType, recordTypeSchema } from './recordType.js';
import { SearchRecord, searchRecordSchema } from './searchRecord.js';

export interface Record {
  searchResult: SearchRecord;
  firstSeenAt?: string | null;
  recordId?: string;
  runId?: string;
  type: RecordType;
  additionalProperties?: Record<string, unknown>;
}

export const recordSchema: Schema<Record> = lazy(() =>
  typedExpandoObject(
    {
      searchResult: ['search_result', searchRecordSchema],
      firstSeenAt: ['first_seen_at', optional(nullable(string()))],
      recordId: ['record_id', optional(string())],
      runId: ['run_id', optional(string())],
      type: ['type', recordTypeSchema],
    },
    'additionalProperties',
    optional(unknown())
  )
);
