/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for RequestStatus
 */
export enum RequestStatus {
  Ok = 'ok',
  Failed = 'failed',
}

/**
 * Schema for RequestStatus
 */
export const requestStatusSchema: Schema<RequestStatus> = stringEnum(
  RequestStatus
);
