/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { RunStatus, runStatusSchema } from './runStatus.js';

export interface Run {
  completedAt?: string | null;
  /**
   * The lowest `record_id` this run produced. Records are not contiguous; use
   * `record_count` for the count.
   */
  firstRecordId?: string;
  /**
   * The highest `record_id` this run produced. Records are not contiguous; use
   * `record_count` for the count.
   */
  lastRecordId?: string;
  monitorId?: string;
  recordCount?: bigint;
  requestsFailed?: bigint;
  requestsOk?: bigint;
  requestsTotal?: bigint;
  runId?: string;
  startedAt?: string | null;
  status: RunStatus;
  /** Prose for a human, empty when completed. */
  statusReason?: string;
  additionalProperties?: Record<string, unknown>;
}

export const runSchema: Schema<Run> = typedExpandoObject(
  {
    completedAt: ['completed_at', optional(nullable(string()))],
    firstRecordId: ['first_record_id', optional(string())],
    lastRecordId: ['last_record_id', optional(string())],
    monitorId: ['monitor_id', optional(string())],
    recordCount: ['record_count', optional(bigint())],
    requestsFailed: ['requests_failed', optional(bigint())],
    requestsOk: ['requests_ok', optional(bigint())],
    requestsTotal: ['requests_total', optional(bigint())],
    runId: ['run_id', optional(string())],
    startedAt: ['started_at', optional(nullable(string()))],
    status: ['status', runStatusSchema],
    statusReason: ['status_reason', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
