/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { RequestStatus, requestStatusSchema } from './requestStatus.js';

/** One run's outcome for one search request. */
export interface RunRequest {
  completedAt?: string | null;
  newRecords?: bigint;
  /** Why the request failed, empty when it succeeded. Not machine-readable. */
  reason?: string;
  requestId?: string;
  resultsReturned?: bigint;
  status: RequestStatus;
  additionalProperties?: Record<string, unknown>;
}

export const runRequestSchema: Schema<RunRequest> = typedExpandoObject(
  {
    completedAt: ['completed_at', optional(nullable(string()))],
    newRecords: ['new_records', optional(bigint())],
    reason: ['reason', optional(string())],
    requestId: ['request_id', optional(string())],
    resultsReturned: ['results_returned', optional(bigint())],
    status: ['status', requestStatusSchema],
  },
  'additionalProperties',
  optional(unknown())
);
