/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for RunState2
 */
export enum RunState2 {
  Idle = 'idle',
  Running = 'running',
  Unknown = 'unknown',
}

/**
 * Schema for RunState2
 */
export const runState2Schema: Schema<RunState2> = stringEnum(RunState2);
