/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for RunStatus
 */
export enum RunStatus {
  Completed = 'completed',
  Partial = 'partial',
  Failed = 'failed',
  Skipped = 'skipped',
}

/**
 * Schema for RunStatus
 */
export const runStatusSchema: Schema<RunStatus> = stringEnum(RunStatus);
