/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for RunState
 */
export enum RunState {
  Idle = 'idle',
  Running = 'running',
  Unknown = 'unknown',
}

/**
 * Schema for RunState
 */
export const runStateSchema: Schema<RunState> = stringEnum(RunState);
