/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface Schedule {
  cadence: string;
  additionalProperties?: Record<string, unknown>;
}

export const scheduleSchema: Schema<Schedule> = typedExpandoObject(
  { cadence: ['cadence', string()] },
  'additionalProperties',
  optional(unknown())
);
