/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Document, documentSchema } from './document.js';
import {
  SearchRequestRef,
  searchRequestRefSchema,
} from './searchRequestRef.js';

export interface SearchRecord {
  document?: Document | null;
  /**
   * Only the requests that matched in the run that emitted this record. A record
   * is emitted once, on first sight, so a request that would match it in a later
   * run never attaches to it.
   */
  matchedRequests?: SearchRequestRef[];
  additionalProperties?: Record<string, unknown>;
}

export const searchRecordSchema: Schema<SearchRecord> = lazy(() =>
  typedExpandoObject(
    {
      document: ['document', optional(nullable(documentSchema))],
      matchedRequests: [
        'matched_requests',
        optional(array(searchRequestRefSchema)),
      ],
    },
    'additionalProperties',
    optional(unknown())
  )
);
