/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface SearchRequestRef {
  /**
   * The request's query text, carried here so a record can be rendered without
   * a second lookup.
   */
  query?: string;
  requestId?: string;
  additionalProperties?: Record<string, unknown>;
}

export const searchRequestRefSchema: Schema<SearchRequestRef> = typedExpandoObject(
  {
    query: ['query', optional(string())],
    requestId: ['request_id', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
