/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Document, documentSchema } from './document.js';

export interface SearchResponse {
  /** Documents that are most relevant to the query */
  documents?: Document[];
  additionalProperties?: Record<string, unknown>;
}

export const searchResponseSchema: Schema<SearchResponse> = lazy(() =>
  typedExpandoObject(
    { documents: ['documents', optional(array(documentSchema))] },
    'additionalProperties',
    optional(unknown())
  )
);
