/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** One passage selected from a document's body. */
export interface Snippet {
  text?: string | null;
  additionalProperties?: Record<string, unknown>;
}

export const snippetSchema: Schema<Snippet> = typedExpandoObject(
  { text: ['text', optional(nullable(string()))] },
  'additionalProperties',
  optional(unknown())
);
