/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  nullable,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Monitor, monitorSchema } from './monitor.js';

export interface UpdateMonitorResponse {
  monitor?: Monitor | null;
  additionalProperties?: Record<string, unknown>;
}

export const updateMonitorResponseSchema: Schema<UpdateMonitorResponse> = lazy(
  () =>
    typedExpandoObject(
      { monitor: ['monitor', optional(nullable(monitorSchema))] },
      'additionalProperties',
      optional(unknown())
    )
);
