/**
 * Seltz APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { MonitorStatus, monitorStatusSchema } from './monitorStatus.js';
import { SearchRequest, searchRequestSchema } from './searchRequest.js';
import { Webhook1, webhook1Schema } from './webhook1.js';

export interface UpdateMonitorRequest {
  cadence: string;
  apiKey?: string | null;
  monitorId?: string;
  name?: string | null;
  /**
   * Replaces the list wholesale when set. An empty list is read as "not set"
   * and keeps the current requests. A request keeps its id and its health when
   * every field of its body is unchanged.
   */
  searchRequests?: SearchRequest[];
  status?: MonitorStatus;
  webhook?: Webhook1 | null;
  additionalProperties?: Record<string, unknown>;
}

export const updateMonitorRequestSchema: Schema<UpdateMonitorRequest> = lazy(
  () =>
    typedExpandoObject(
      {
        cadence: ['cadence', string()],
        apiKey: ['api_key', optional(nullable(string()))],
        monitorId: ['monitor_id', optional(string())],
        name: ['name', optional(nullable(string()))],
        searchRequests: [
          'search_requests',
          optional(array(searchRequestSchema)),
        ],
        status: ['status', optional(monitorStatusSchema)],
        webhook: ['webhook', optional(nullable(webhook1Schema))],
      },
      'additionalProperties',
      optional(unknown())
    )
);
